spring:
  datasource:
    url: jdbc:mysql://47.99.136.163/share_user_center
    hikari:
      username: root
      password: 123456
      # >= 6.x com.mysql.cj.jdbc.Driver
      # <=5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver