spring:
  datasource:
    url: jdbc:mysql://47.99.136.163:3306/share_content_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456

server:
  port: 8010
