spring:
  datasource:
    url: jdbc:mysql://47.99.136.163:3306/share_content_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  cloud:
    nacos:
      discovery:
        #nacos service 地址
        server-addr: 192.168.0.105:8848
  application:
    name: content-center
server:
  port: 8010
